//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://schemas.datacontract.org/2004/07/unoProyectServidor")]
    [System.SerializableAttribute()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICredentialsManager")]
    public interface ICredentialsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICredentialsManager/LogIn", ReplyAction="http://tempuri.org/ICredentialsManager/LogInResponse")]
        bool LogIn(Logic.ServiceReference1.Credentials credentialsReceived);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICredentialsManager/LogIn", ReplyAction="http://tempuri.org/ICredentialsManager/LogInResponse")]
        System.Threading.Tasks.Task<bool> LogInAsync(Logic.ServiceReference1.Credentials credentialsReceived);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICredentialsManager/SignUp", ReplyAction="http://tempuri.org/ICredentialsManager/SignUpResponse")]
        int SignUp(Logic.ServiceReference1.Credentials credentialsReceived);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICredentialsManager/SignUp", ReplyAction="http://tempuri.org/ICredentialsManager/SignUpResponse")]
        System.Threading.Tasks.Task<int> SignUpAsync(Logic.ServiceReference1.Credentials credentialsReceived);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICredentialsManagerChannel : Logic.ServiceReference1.ICredentialsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CredentialsManagerClient : System.ServiceModel.ClientBase<Logic.ServiceReference1.ICredentialsManager>, Logic.ServiceReference1.ICredentialsManager {
        
        public CredentialsManagerClient() {
        }
        
        public CredentialsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CredentialsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CredentialsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CredentialsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogIn(Logic.ServiceReference1.Credentials credentialsReceived) {
            return base.Channel.LogIn(credentialsReceived);
        }
        
        public System.Threading.Tasks.Task<bool> LogInAsync(Logic.ServiceReference1.Credentials credentialsReceived) {
            return base.Channel.LogInAsync(credentialsReceived);
        }
        
        public int SignUp(Logic.ServiceReference1.Credentials credentialsReceived) {
            return base.Channel.SignUp(credentialsReceived);
        }
        
        public System.Threading.Tasks.Task<int> SignUpAsync(Logic.ServiceReference1.Credentials credentialsReceived) {
            return base.Channel.SignUpAsync(credentialsReceived);
        }
    }
}
