//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unoProyect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_es_MX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es_MX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unoProyect.Properties.Resources.es-MX", typeof(Resources_es_MX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviaremos un código a tu correo electrónico para cambiar tu contraseña.
        /// </summary>
        internal static string instructionChangePasswordCode {
            get {
                return ResourceManager.GetString("instructionChangePasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No ves el código? Revisa tu carpeta de correos no deseados.
        /// </summary>
        internal static string instructionCheckSpam {
            get {
                return ResourceManager.GetString("instructionCheckSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código:.
        /// </summary>
        internal static string instructionEnterConfirmCode {
            get {
                return ResourceManager.GetString("instructionEnterConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar código de invitación.
        /// </summary>
        internal static string instructionEnterInvitationCode {
            get {
                return ResourceManager.GetString("instructionEnterInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa nueva contraseña.
        /// </summary>
        internal static string instructionEnterNewPassword {
            get {
                return ResourceManager.GetString("instructionEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar nombre de usuario.
        /// </summary>
        internal static string instructionEnterUsername {
            get {
                return ResourceManager.GetString("instructionEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres abandonar la partida?.
        /// </summary>
        internal static string instructionExitGame {
            get {
                return ResourceManager.GetString("instructionExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repite la nueva contraseña.
        /// </summary>
        internal static string instructionRepeatPassword {
            get {
                return ResourceManager.GetString("instructionRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar código por correo electrónico.
        /// </summary>
        internal static string instructionSendCodeByEmail {
            get {
                return ResourceManager.GetString("instructionSendCodeByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviaremos un código a tu correo electrónico para confirmar el registro.
        /// </summary>
        internal static string instructionSendConfirmCode {
            get {
                return ResourceManager.GetString("instructionSendConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de espera.
        /// </summary>
        internal static string lobby {
            get {
                return ResourceManager.GetString("lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        internal static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como invitado.
        /// </summary>
        internal static string playAsGuest {
            get {
                return ResourceManager.GetString("playAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar amigos.
        /// </summary>
        internal static string playWithFriends {
            get {
                return ResourceManager.GetString("playWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar nuevo código.
        /// </summary>
        internal static string requestNewCode {
            get {
                return ResourceManager.GetString("requestNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar código de invitación.
        /// </summary>
        internal static string sendCode {
            get {
                return ResourceManager.GetString("sendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar perfil.
        /// </summary>
        internal static string settingsProfile {
            get {
                return ResourceManager.GetString("settingsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar partida.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de la partida es:.
        /// </summary>
        internal static string theGameCodeIs {
            get {
                return ResourceManager.GetString("theGameCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
